### ISSUE TITLE
Error handling for various inputs

### ISSUE THREAD

**Issue by ghost** [limeburst/isbn-rs#6]
Attempting to parse empty str ("") or nonsense like "L" causes a panic. They should instead return errors.

**Comment by billop** [comment]
I was working on a PR but I ran into a peculiarity: `Parser` will simply convert anything weird into a 0:
```rust
_ => Some(c.to_digit(10).unwrap_or(0) as u8),
```
This means that an input of 
```rust
"ⱧňᚥɂᛢĞžᚪ©ᛟƚ¶G".parse::<isbn::Isbn13>()?
```
will not raise any errors.

Is this a part of the ISBN specification or something?

**Comment by limeburst** [comment]
This is actually a [known issue](https://www.reddit.com/r/rust/comments/afhmaf/isbnrs_now_supports_no_std_and_hyphenation/ee142r6/?context=3) that hasn't been fixed yet. Thanks for creating an issue for it anyway!

**Comment by assarbad** [comment]
Just ran into this as well with `"5"` as the alleged ISBN. Especially the fact that it panics makes it hard to use. I don't know how to circumvent this, because I need to be able to parse either form of ISBNs (10 or 13) and I have a few bad inputs in the list — how to avoid the panic is beyond me.

**Comment by limeburst** [comment]
I've abandoned this package for way too long 😢

I'll merge pending pull requests including the fix for this issue, do some housekeeping and make a new release.

Thanks and apologies to people who waited for so long, especially @philippeitis and @bpeel 🙏

**Comment by limeburst** [comment]
Ok, I've merged changes from @philippeitis's `isbn2` crate, so now crate `isbn` and `isbn2` are identical.

Also sent @philippeitis invites as maintainer for this repository and crates.io crate owner. I'm open to creating a new GitHub organization to house both https://github.com/limeburst/isbn-rs and https://github.com/limeburst/isbn-ranges!
